# Generated by Django 5.0.3 on 2024-04-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ath_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(default=0)),
                ('ath_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField(max_length=100)),
                ('event_fee', models.IntegerField(default=0)),
                ('sports_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('phone_number', models.IntegerField(default=0)),
                ('event_location', models.CharField(max_length=100)),
            ],
        ),
    ]
