# Generated by Django 5.0.3 on 2024-04-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_sport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='phone_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='ath_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='ath_name',
            new_name='name',
        ),
    ]
